# Generated by Django 2.2 on 2019-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biljnevrsteapp', '0002_auto_20190514_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slika',
            name='naziv_slike',
            field=models.ImageField(upload_to=''),
        ),
    ]
